#pragma config(Sensor, dgtl1,  liftBottomTouch, sensorTouch)
#pragma config(Sensor, dgtl2,  liftTopTouch,   sensorTouch)
#pragma config(Sensor, dgtl3,  autoButton, sensorTouch)
#pragma config(Motor,  port2,           left,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           ball1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           ball2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           lift1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           tread,         tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

short side = 1;//-1 is red, 1 is blue
short area = 1; //1 is big side, -1 is small side

int treadCount=0, dumpCount=0;//for conveinience features
int INPUT[2][5]; //left1, left2, right1, right2, ball, lift

//Auto Sequencing
int AUTO11[5][12]={//bigger side big balls
	{0,127,90,-127*side,140,127,260, 127*side,390,127,590,0},//left
	{0,127,90, 127*side,140,127,260,-127*side,390,127,590,0},//right
	{0,127,200,0,0,0,0,0,0,0,0,0},//lift
	{0,-127,100,0,550,127,640,0,0,0,0,0},//ball
	{0,0,0,0,0,0,0,0,0,0,0,0}};//tread

int AUTO12[5][12]={//bigger side get 3 small balls
	{0,127,250,-127*side,300,127,420, 127*side,550,127,750,0},//left
	{0,127,250, 127*side,300,127,420,-127*side,550,127,750,0},//right
	{0,127,200,0,550,-127,730,0,0,0,0,0},//lift
	{0,-127,100,0,550,127,640,0,0,0,0,0},//ball
	{0,0,0,0,0,0,0,0,0,0,0,0}};//tread

int AUTO21[5][12]={//small side 2 small balls
	{0,0,250,127,320,0,370,-127,460,0,0,0},//left
	{0,0,250,127,320,0,370,-127,460,0,0,0},//right
	{0,0,0,0,0,0,0,0,0,0,0,0},//lift
	{0,-127,250,0,330,127,0,0,530,0,670,0},//ball
	{0,0,0,0,0,0,0,0,490,-127,1000,0}};//tread

int AUTO22[5][20]={//small side 2 big balls
	{0,127,80, 127*side,127,127,250, 127*side,296,127,430,-127*side,530,127,580, 127*side,660,127,810,0},//left
	{0,127,80,-127*side,127,127,250,-127*side,296,127,430, 127*side,530,127,580,-127*side,660,127,810,0},//right
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},//lift
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},//ball
	{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};//tread

int AUTOLOL[5][12]={//aggressive defense manuever
	{0,127,800,-127,1300,0,0,0,0,0,0,0},//left
	{0,127,800,-127,1300,0,0,0,0,0,0,0},//right
	{0,0,0,0,0,0,0,0,0,0,0,0},//lift
	{0,-127,150,0,800,-127,950,0,0,0,0,0},//ball
	{0,0,0,0,0,0,0,0,0,0,0,0}};//tread

void controller1()
{
	//movement
		if (vexRT[Ch1] != 0){
			INPUT[0][0]  = (vexRT[Ch3] + vexRT[Ch1]) / 2;
			INPUT[0][1]  = (vexRT[Ch3] - vexRT[Ch1]) / 2;
		}
		else {
			INPUT[0][0]  = vexRT[Ch3] + vexRT[Ch1];
			INPUT[0][1]  = vexRT[Ch3] - vexRT[Ch1];
		}
		//lift motors
		if (vexRT[Btn5U] == 1)
			INPUT[0][3] = 127;
		else if (vexRT[Btn5D] == 1)
			INPUT[0][3] = -127;
		else
			INPUT[0][3] =0;
		//ball motors
		if (vexRT[Btn6U] == 1)
			INPUT[0][2] = 127;
		else if (vexRT[Btn6D] == 1)
			INPUT[0][2] =-127;
		else
			INPUT[0][2] = 0;
		//tread motors
		if (vexRT[Btn7U] == 1)
			INPUT[0][4] = 127;
		else if (vexRT[Btn7D]==1)
			INPUT[0][4] = -127;
		else
			INPUT[0][4] = 0;
		//dump balls
		if (vexRT[Btn7L] == 1)
			dumpCount = 350;
}

void controller2()
{
		//movement
		if (vexRT[Ch1Xmtr2] != 0)
		{
			INPUT[1][0]  = (vexRT[Ch3Xmtr2] + vexRT[Ch1Xmtr2]) / 2;
			INPUT[1][1]  = (vexRT[Ch3Xmtr2] - vexRT[Ch1Xmtr2]) / 2;
		}
		else {
			INPUT[1][0]  = vexRT[Ch3Xmtr2] + vexRT[Ch1Xmtr2];
			INPUT[1][1]  = vexRT[Ch3Xmtr2] - vexRT[Ch1Xmtr2];
		}
		//lift motors
		if (vexRT[Btn5UXmtr2] == 1)
			INPUT[1][3] = 127;
		else if (vexRT[Btn5DXmtr2] == 1)
			INPUT[1][3] = -127;
		else
			INPUT[1][3] = 0;
		//ball motors
		if (vexRT[Btn6UXmtr2] == 1)
			INPUT[1][2] = 127;
		else if (vexRT[Btn6DXmtr2] == 1)
			INPUT[1][2] = -127;
		else
			INPUT[1][2] = 0;
		//tread motors
		if (vexRT[Btn7UXmtr2] == 1)
			INPUT[1][4] = 127;
		else if (vexRT[Btn7DXmtr2]==1)
			INPUT[1][4] = -127;
		else
			INPUT[1][4] = 0;
		//dump balls
		if (vexRT[Btn7L] == 1)
			dumpCount = 350;
}

void setMotors()
{
	if (INPUT[0][2]>0 || INPUT[1][2]>0)
		treadCount = 300;

	if (dumpCount>0)
		dumpCount--;

	if (INPUT[0][0]!=0 || INPUT[0][1]!=0)//move motors
	{
		motor[left]  = INPUT[0][0];
		motor[right]  = INPUT[0][1];
	}
	else
	{
		motor[left] = INPUT[1][0];
		motor[right] = INPUT[1][1];
	}

	if (INPUT[0][2]!=0)//ball motors
	{
		motor[ball1]  = INPUT[0][2];
		motor[ball2]  = INPUT[0][2];
	}
	else if (INPUT[1][2]!=0)
	{
		motor[ball1]  = INPUT[1][2];
		motor[ball2]  = INPUT[1][2];
	}
	else if (dumpCount>250)
	{
		motor[ball1]  = 127;
		motor[ball2]  = 127;
	}
	else
	{
		motor[ball1]  = 0;
		motor[ball2]  = 0;
	}

	if (INPUT[0][4]!=0)
	{
		motor[tread] = INPUT[0][4];
	}
	else if (INPUT[1][4]!=0)
	{
		motor[tread] = INPUT[1][4];
	}
	else if (dumpCount != 0)
	{
		motor[tread] = -127;
	}
	else if (treadCount!=0)
	{
		motor[tread] = 127;
		treadCount--;
	}
	else
	{
		motor[tread]=0;
	}

	if (INPUT[0][3]>0 && SensorValue(liftTopTouch)==0)
	{
			motor[lift1] = INPUT[0][3];
			motor[lift2] = INPUT[0][3];
	}
	else if (INPUT[0][3]<0 && SensorValue(liftBottomTouch)==0)
	{
			motor[lift1] = INPUT[0][3];
			motor[lift2] = INPUT[0][3];
	}
	else if (INPUT[1][3]>0 && SensorValue(liftTopTouch)==0)
	{
			motor[lift1] = INPUT[1][3];
			motor[lift2] = INPUT[1][3];
	}
	else if (INPUT[1][3]<0 && SensorValue(liftBottomTouch)==0)
	{
			motor[lift1] = INPUT[1][3];
			motor[lift2] = INPUT[1][3];
	}
	else
	{
		motor[lift1] = 0;
		motor[lift2] = 0;
	}
}

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{
	bool buttonRelease = true;
	short mode = 0;
	int count = 0;
	while(true)
	{
		if (SensorValue(autoButton)==1 && buttonRelease == true)
		{
			buttonRelease = false;
		}
		else if (SensorValue(autoButton)==0 && buttonRelease == false)
		{
			buttonRelease = true;
			mode++;
			count = 0;
		}
		if (area == 1)//big area code
		{
			if (mode%2 == 0)
			{
				for (int i=5;i>=0;i--)
				{
					if (AUTO11[0][i*2]==count)
						motor[left]=AUTO11[0][i*2+1];
					if (AUTO11[1][i*2]==count)
						motor[right]=AUTO11[1][i*2+1];
					if (AUTO11[2][i*2]==count)
					{
						motor[lift1]=AUTO11[2][i*2+1];
						motor[lift2]=AUTO11[2][i*2+1];
					}
					if (AUTO11[3][i*2]==count)
					{
						motor[ball1]=AUTO11[3][i*2+1];
						motor[ball2]=AUTO11[3][i*2+1];
					}
					if (AUTO11[4][i*2]==count)
						motor[tread]=AUTO11[4][i*2+1];
				}
			}
			else if (mode%2 == 1)
			{
				for (int i=5;i>=0;i--)
				{
					if (AUTO12[0][i*2]==count)
						motor[left]=AUTO12[0][i*2+1];
					if (AUTO12[1][i*2]==count)
						motor[right]=AUTO12[1][i*2+1];
					if (AUTO12[2][i*2]==count)
					{
						motor[lift1]=AUTO12[2][i*2+1];
						motor[lift2]=AUTO12[2][i*2+1];
					}
					if (AUTO12[3][i*2]==count)
					{
						motor[ball1]=AUTO12[3][i*2+1];
						motor[ball2]=AUTO12[3][i*2+1];
					}
					if (AUTO12[4][i*2]==count)
						motor[tread]=AUTO12[4][i*2+1];
				}
			}
		}
		else if (area == -1)
		{
			if (mode%2 == 0)
			{
				for (int i=5;i>=0;i--)
				{
					if (AUTO21[0][i*2]==count)
						motor[left]=AUTO21[0][i*2+1];
					if (AUTO21[1][i*2]==count)
						motor[right]=AUTO21[1][i*2+1];
					if (AUTO21[2][i*2]==count)
					{
						motor[lift1]=AUTO21[2][i*2+1];
						motor[lift2]=AUTO21[2][i*2+1];
					}
					if (AUTO21[3][i*2]==count)
					{
						motor[ball1]=AUTO21[3][i*2+1];
						motor[ball2]=AUTO21[3][i*2+1];
					}
					if (AUTO21[4][i*2]==count)
						motor[tread]=AUTO21[4][i*2+1];
				}
			}
			else if (mode%2==1)
			{
				for (int i=9;i>=0;i--)
				{
					if (AUTO22[0][i*2]==count)
						motor[left]=AUTO22[0][i*2+1];
					if (AUTO22[1][i*2]==count)
						motor[right]=AUTO22[1][i*2+1];
					if (AUTO22[2][i*2]==count)
					{
						motor[lift1]=AUTO22[2][i*2+1];
						motor[lift2]=AUTO22[2][i*2+1];
					}
					if (AUTO22[3][i*2]==count)
					{
						motor[ball1]=AUTO22[3][i*2+1];
						motor[ball2]=AUTO22[3][i*2+1];
					}
					if (AUTO22[4][i*2]==count)
						motor[tread]=AUTO22[4][i*2+1];
				}
			}
		}
		count++;
		wait1Msec(10);
	}
}

task usercontrol()
{
	while(true)
	{
			controller2();
			controller1();
			setMotors();
			wait1Msec(10);
	}
}
